const dragonList = [
    { name: ["divider", "🌈 熱門龍 🌈"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Lunera", "盧內拉"], traitsEn: ["Quirky", "Quiet"], traitsKo: ["反覆無常的", "冷靜的"], Quirky: [10, 30, 0, 10], Quiet: [0, 10, 25, 10] },
    { name: ["Berris", "貝里斯"], traitsEn: ["Docile", "Smart"], traitsKo: ["溫和的", "聰明的"], Docile: [0, 10, 10, 25], Smart: [10, 0, 0, 30] },
    { name: ["Skink Dragon", "石龍子龍"], traitsEn: ["Adamant", "Docile"], traitsKo: ["固執的", "溫和的"], Adamant: [10, 25, 10, 0], Docile: [0, 15, 15, 30] },
    { name: ["Crested Dragon", "守宮"], traitsEn: ["Lax", "quickWitted"], traitsKo: ["調皮的", "眼尖的"], Lax: [5, 5, 0, 20], quickWitted: [20, 5, 0, 0] },
    { name: ["Egg Dragon", "蛋龍"], traitsEn: ["Adamant", "Docile"], traitsKo: ["固執的", "溫和的"], Adamant: [10, 25, 10, 0], Docile: [0, 5, 5, 20] },
    { name: ["Girdletail Dragon", "鎧蜥龍"], traitsEn: ["Bold", "Rash"], traitsKo: ["大膽的", "莽撞的"], Bold: [10, 30, 0, 0], Rash: [25, 10, 0, 10] },
    { name: ["Sky Lancer", "天空槍兵"], traitsEn: ["Quiet", "Brave"], traitsKo: ["冷靜的", "勇敢的"], Quiet: [0, 10, 20, 10], Brave: [0, 30, 15, 15] },
    { name: ["divider", "🎉 當前活動 🎉"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Caretaker God Dragon", "照護者古代神龍"], traitsEn: ["Docile", "unknown"], traitsKo: ["溫和的", "目前未知"], Docile: [0, 10, 10, 30], unknown: [1, 1, 1, 1] },
    { name: ["God Dragon", "古代神龍"], traitsEn: ["Brave", "Docile"], traitsKo: ["勇敢的", "溫和的"], Brave: [0, 25, 10, 10], Docile: [0, 10, 10, 30] },
    { name: ["Shark Dragon", "鯊龍"], traitsEn: ["Quiet", "Rash"], traitsKo: ["冷靜的", "莽撞的"], Quiet: [0, 5, 20, 5], Rash: [20, 10, 0, 10] },
    { name: ["Mushroom Dragon", "菇龍"], traitsEn: ["Calm", "Docile"], traitsKo: ["沉穩的", "溫和的"], Calm: [10, 0, 25, 10], Docile: [0, 10, 10, 20] },

    { name: ["divider", "🎨 自創龍 🎨"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Voodoo Dragon", "巫毒龍"], traitsEn: ["Quirky", "unknown"], traitsKo: ["反覆無常的(素質尚未確認)", "目前未知)"], Quirky: [0, 1, 0, 0], unknown: [1, 1, 1, 1] },
    { name: ["Frame", "相框龍"], traitsEn: ["Hardy", "Docile"], traitsKo: ["努力的", "溫和的"], Hardy: [0, 10, 20, 0], Docile: [0, 10, 10, 30] },
    { name: ["Gorgon", "戈爾貢"], traitsEn: ["Calm", "quickWitted"], traitsKo: ["沉穩的", "眼尖的"], Calm: [10, 0, 20, 10], quickWitted: [20, 0, 0, 5] },
    { name: ["Pancake Dragon", "鬆餅龍"], traitsEn: ["Docile", "Naive"], traitsKo: ["溫和的", "天真爛漫的"], Docile: [0, 10, 10, 25], Naive: [30, 0, 10, 10] },
    { name: ["Maple Dragon", "楓龍"], traitsEn: ["Naive", "unknown"], traitsKo: ["天真爛漫的", "目前未知"], Naive: [20, 0, 5, 5], unknown: [1, 1, 1, 1] },

    { name: ["divider", "💎 本月龍 💎"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Ranky", "段位者"], traitsEn: ["Naive", "Hardy"], traitsKo: ["天真爛漫的", "努力的"], Naive: [20, 0, 5, 5], Hardy: [0, 0, 20, 5] },
    { name: ["Lumindis", "魯銘迪斯"], traitsEn: ["Bold", "Quiet"], traitsKo: ["大膽的", "冷靜的"], Bold: [5, 20, 0, 0], Quiet: [0, 10, 30, 10] },
    { name: ["Plumos", "梅龍"], traitsEn: ["Hardy", "Calm"], traitsKo: ["努力的", "沉穩的"], Hardy: [0, 0, 20, 5], Calm: [10, 0, 25, 10] },
    { name: ["Angel Cat", "天使貓"], traitsEn: ["Docile", "Brave"], traitsKo: ["溫和的", "勇敢的"], Docile: [0, 10, 10, 25], Brave: [0, 20, 10, 10] },
    { name: ["Stealth Dragon", "隱龍"], traitsEn: ["Quirky", "Adamant"], traitsKo: ["反覆無常的", "固執的"], Quirky: [10, 20, 0, 10], Adamant: [10, 25, 10, 0] },
    { name: ["Rakshasa", "羅剎"], traitsEn: ["quickWitted", "Careful"], traitsKo: ["眼尖的", "慎重的"], quickWitted: [25, 0, 0, 5], Careful: [10, 10, 20, 0] },
    { name: ["Solucanis", "索盧卡尼斯"], traitsEn: ["Bold", "Hasty"], traitsKo: ["大膽的", "急躁的"], Bold: [0, 30, 10, 0], Hasty: [20, 10, 10, 0] },
    
    { name: ["divider", "⭐ 活動節日 ⭐"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Abaddon", "亞巴頓"], traitsEn: ["Adamant", "Quiet"], traitsKo: ["固執的", "冷靜的"], Adamant: [15, 30, 15, 0], Quiet: [0, 10, 20, 10] },
    { name: ["Cupi Friend", "邱比特友情龍"], traitsEn: ["Brave", "Hardy"], traitsKo: ["勇敢的", "努力的"], Brave: [0, 20, 5, 5], Hardy: [0, 0, 25, 0] },
    { name: ["Pangpang", "胖胖"], traitsEn: ["Hardy", "quickWitted"], traitsKo: ["努力的", "眼尖的"], Hardy: [0, 10, 10, 0], quickWitted: [30, 0, 10, 0] },
    { name: ["Kangkang", "江江"], traitsEn: ["quickWitted", "Bold"], traitsKo: ["眼尖的", "大膽的"], quickWitted: [25, 0, 0, 5], Bold: [0, 25, 0, 5] },
    { name: ["Sullae", "水來"], traitsEn: ["Quirky", "Adamant"], traitsKo: ["反覆無常的", "固執的"], Quirky: [25, 0, 0, 5], Adamant: [0, 25, 0, 5] },
    { name: ["Eshu", "艾舒"], traitsEn: ["Quirky", "Naive"], traitsKo: ["反覆無常的", "天真爛漫的"], Quirky: [10, 25, 0, 10], Naive: [30, 0, 15, 15] },
    { name: ["Zombie Dragon", "殭屍"], traitsEn: ["Hasty", "Rash"], traitsKo: ["急躁的", "莽撞的"], Hasty: [20, 5, 5, 0], Rash: [25, 10, 0, 10] },
    { name: ["Bearded Dragon", "鬃獅蜥龍"], traitsEn: ["Bold", "Smart"], traitsKo: ["大膽的", "聰明的"], Bold: [0, 30, 0, 10], Smart: [0, 10, 0, 30] },
    { name: ["Caretaker God Dragon", "照護者古代神龍"], traitsEn: ["Docile", "unknown"], traitsKo: ["溫和的", "目前未知"], Docile: [0, 10, 10, 30], unknown: [1, 1, 1, 1] },

    { name: ["divider", "🎟️ 一代序號 🎟️"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Porta", "普爾塔"], traitsEn: ["Calm", "Brave"], traitsKo: ["沉穩的", "勇敢的"], Calm: [10, 0, 25, 10], Brave: [0, 30, 10, 10] },
    { name: ["Feros", "費洛斯"], traitsEn: ["Smart", "Careful"], traitsKo: ["聰明的", "慎重的"], Smart: [10, 0, 0, 30], Careful: [10, 10, 30, 0] },
    { name: ["Dianu", "迪亞努"], traitsEn: ["Quiet", "Adamant"], traitsKo: ["冷靜的", "固執的"], Quiet: [0, 10, 30, 10], Adamant: [10, 25, 10, 0] },
    { name: ["Dimension Dragon", "次元龍"], traitsEn: ["Smart", "Bold"], traitsKo: ["聰明的", "大膽的"], Smart: [10, 0, 0, 30], Bold: [0, 30, 0, 0] },

    { name: ["divider", "🎫 二代序號 🎫"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Hela", "海拉"], traitsEn: ["Quirky", "Smart"], traitsKo: ["反覆無常的", "聰明的"], Quirky: [10, 30, 0, 10], Smart: [0, 10, 0, 30] },
    { name: ["Nidhogg", "尼德霍格"], traitsEn: ["quickWitted", "Bold"], traitsKo: ["眼尖的", "大膽的"], quickWitted: [25, 5, 0, 0], Bold: [0, 30, 0, 5] },
    { name: ["Surtr", "火巨龍"], traitsEn: ["Hasty", "Adamant"], traitsKo: ["急躁的", "固執的"], Hasty: [30, 10, 10, 0], Adamant: [15, 30, 15, 0] },
    { name: ["Ragnarok", "末日龍"], traitsEn: ["Quiet", "Adamant"], traitsKo: ["冷靜的", "固執的"], Quiet: [0, 10, 25, 10], Adamant: [15, 30, 15, 0] },
    
    { name: ["divider", "📒 收藏書 📒"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Rude Ore", "原礦龍"], traitsEn: ["Calm", "Quiet"], traitsKo: ["沉穩的", "冷靜的"], Calm: [15, 0, 30, 15], Quiet: [0, 15, 30, 15] },

    { name: ["divider", "🪐 艾弗利亞 🌌"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Dark God Dragon", "黑暗古代神龍"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Dark Angel Dragon", "黑暗天使龍"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Dark Lightning Dragon", "黑暗閃電古龍"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Snow Frost Dragon", "雪霜冰河古龍"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Ｍaniacal Power Dragon", "瘋狂力龍"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Jealousy Cupid", "忌妒邱比特龍"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Gold AppleCheek", "黃金蘋果肌龍"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
   
    { name: ["divider", "☀️ 東四神龍 ☀️"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Power Dragon", "力龍"], traitsEn: ["Smart", "Calm"], traitsKo: ["聰明的", "沉穩的"], Smart: [0, 0, 0, 25], Calm: [10, 0, 25, 10] },
    { name: ["Frost Dragon", "冰河古龍"], traitsEn: ["Careful", "Quiet"], traitsKo: ["慎重的", "冷靜的"], Careful: [10, 10, 20, 0], Quiet: [0, 10, 20, 10] },
    { name: ["Lightning Dragon", "閃電古龍"], traitsEn: ["Brave", "Bold"], traitsKo: ["勇敢的", "大膽的"], Brave: [0, 30, 10, 10], Bold: [0, 30, 5, 0] },
    { name: ["God Dragon", "古代神龍"], traitsEn: ["Brave", "Docile"], traitsKo: ["勇敢的", "溫和的"], Brave: [0, 25, 10, 10], Docile: [0, 10, 10, 30] },
    { name: ["Darknix", "黑暗尼斯"], traitsEn: ["Quiet", "Careful"], traitsKo: ["冷靜的", "慎重的"], Quiet: [0, 15, 30, 15], Careful: [15, 15, 30, 0] },
   
    { name: ["divider", "🌙 西四神龍 🌙"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Florea", "芙蘿蕾"], traitsEn: ["Careful", "Smart"], traitsKo: ["慎重的", "聰明的"], Careful: [10, 10, 25, 0], Smart: [5, 0, 0, 30] },
    { name: ["Fides", "菲達斯"], traitsEn: ["Adamant", "Bold"], traitsKo: ["固執的", "大膽的"], Adamant: [10, 30, 10, 0], Bold: [5, 30, 0, 0] },
    { name: ["Lucio", "盧西歐"], traitsEn: ["quickWitted", "Quiet"], traitsKo: ["眼尖的", "冷靜的"], quickWitted: [30, 5, 0, 0], Quiet: [0, 15, 30, 15] },
    { name: ["Obex", "歐沛克斯"], traitsEn: ["Careful", "Quirky"], traitsKo: ["慎重的", "反覆無常的"], Careful: [15, 15, 30, 0], Quirky: [15, 30, 0, 15] },
    { name: ["Non", "虛無"], traitsEn: ["quickWitted", "Quiet"], traitsKo: ["眼尖的", "冷靜的"], quickWitted: [30, 10, 0, 0], Quiet: [0, 15, 30, 15] },

    { name: ["divider", "🔥 東尤塔勘 💧"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Pierrot Dragon", "小丑"], traitsEn: ["Lax", "Smart"], traitsKo: ["調皮的", "聰明的"], Lax: [10, 10, 0, 30], Smart: [0, 0, 5, 20] },
    { name: ["Seere", "系爾"], traitsEn: ["Naive", "Quirky"], traitsKo: ["天真爛漫的", "反覆無常的"], Naive: [20, 0, 15, 15], Quirky: [10, 20, 0, 10] },
    { name: ["Cupid", "邱比特"], traitsEn: ["Naive", "Hardy"], traitsKo: ["天真爛漫的", "努力的"], Naive: [30, 0, 10, 10], Hardy: [0, 0, 25, 0] },
    { name: ["Nebula", "星雲"], traitsEn: ["Quiet", "Careful"], traitsKo: ["冷靜的", "慎重的"], Quiet: [0, 10, 30, 10], Careful: [10, 10, 25, 0] },
    { name: ["Party Dragon", "派對龍"], traitsEn: ["Lax", "Naive"], traitsKo: ["調皮的", "天真爛漫的"], Lax: [15, 15, 0, 30], Naive: [30, 0, 10, 10] },
    { name: ["Angel Dragon", "天使龍"], traitsEn: ["Docile", "Calm"], traitsKo: ["溫和的", "沉穩的"], Docile: [0, 10, 10, 30], Calm: [10, 0, 30, 10] },
    { name: ["White Thunder Dragon", "白雷龍"], traitsEn: ["Hasty", "Bold"], traitsKo: ["急躁的", "大膽的"], Hasty: [30, 10, 10, 0], Bold: [0, 30, 5, 0] },
    { name: ["Underground Dragon", "地道龍"], traitsEn: ["Quiet", "Bashful"], traitsKo: ["冷靜的", "害羞的"], Quiet: [0, 10, 25, 10], Bashful: [10, 0, 10, 20] },
    { name: ["Rafael", "拉斐爾"], traitsEn: ["Docile", "Hardy"], traitsKo: ["溫和的", "努力的"], Docile: [0, 10, 10, 30], Hardy: [0, 0, 20, 0] },
    { name: ["Centipede Dragon", "蜈蚣龍"], traitsEn: ["Quirky", "Careful"], traitsKo: ["反覆無常的", "慎重的"], Quirky: [15, 30, 0, 15], Careful: [10, 10, 25, 0] },
    { name: ["Lunera", "盧內拉"], traitsEn: ["Quirky", "Quiet"], traitsKo: ["反覆無常的", "冷靜的"], Quirky: [10, 30, 0, 10], Quiet: [0, 10, 25, 10] },
    { name: ["Emerald Dragon", "翡翠龍"], traitsEn: ["Brave", "Calm"], traitsKo: ["勇敢的", "沉穩的"], Brave: [0, 30, 15, 15], Calm: [10, 0, 20, 10] },
    { name: ["Insect Queen", "蟲后"], traitsEn: ["quickWitted", "Smart"], traitsKo: ["眼尖的", "聰明的"], quickWitted: [30, 0, 5, 0], Smart: [0, 10, 0, 30] },
    { name: ["Skink Dragon", "石龍子龍"], traitsEn: ["Adamant", "Docile"], traitsKo: ["固執的", "溫和的"], Adamant: [10, 25, 10, 0], Docile: [0, 15, 15, 30] },
    { name: ["Black Armor", "黑甲龍"], traitsEn: ["Bold", "Adamant"], traitsKo: ["大膽的", "固執的"], Bold: [0, 30, 0, 10], Adamant: [15, 30, 15, 0] },
    { name: ["Zephyros", "澤費羅斯龍"], traitsEn: ["Quirky", "Adamant"], traitsKo: ["反覆無常的", "固執的"], Quirky: [10, 25, 0, 10], Adamant: [10, 30, 10, 0] },
    { name: ["Iron Dragon", "鋼鐵龍"], traitsEn: ["Quiet", "Quirky"], traitsKo: ["冷靜的", "反覆無常的"], Quiet: [0, 5, 20, 5], Quirky: [15, 30, 0, 15] },
    { name: ["Applecheek", "蘋果肌"], traitsEn: ["quickWitted", "Bashful"], traitsKo: ["眼尖的", "害羞的"], quickWitted: [20, 5, 0, 0], Bashful: [10, 0, 10, 20] },
    { name: ["Slime Dragon", "史萊姆龍"], traitsEn: ["Quirky", "Lax"], traitsKo: ["反覆無常的", "調皮的"], Quirky: [15, 30, 0, 15], Lax: [15, 15, 0, 30] },
    { name: ["Voncias", "風霞斯"], traitsEn: ["Docile", "Naive"], traitsKo: ["溫和的", "天真爛漫的"], Docile: [0, 10, 10, 30], Naive: [30, 0, 10, 10] },
    { name: ["Leopard Dragon", "豹龍"], traitsEn: ["Careful", "Brave"], traitsKo: ["慎重的", "勇敢的"], Careful: [15, 15, 30, 0], Brave: [0, 30, 15, 15] },
    { name: ["Rupia", "路皮亞"], traitsEn: ["Docile", "Smart"], traitsKo: ["溫和的", "聰明的"], Docile: [0, 10, 10, 30], Smart: [10, 0, 0, 30] },
    { name: ["Hurricane Dragon", "颶風龍"], traitsEn: ["quickWitted", "Quirky"], traitsKo: ["眼尖的", "反覆無常的"], quickWitted: [20, 0, 0, 0], Quirky: [15, 30, 0, 15] },
    { name: ["Shark Dragon", "鯊龍"], traitsEn: ["Quiet", "Rash"], traitsKo: ["冷靜的", "莽撞的"], Quiet: [0, 5, 20, 5], Rash: [20, 10, 0, 10] },
    { name: ["Bomber Dragon", "轟炸龍"], traitsEn: ["Naive", "Lax"], traitsKo: ["天真爛漫的", "調皮的"], Naive: [30, 0, 10, 10], Lax: [10, 10, 0, 30] },
    { name: ["Henes", "軒尼斯"], traitsEn: ["Careful", "Adamant"], traitsKo: ["慎重的", "固執的"], Careful: [15, 15, 30, 0], Adamant: [15, 30, 15, 0] },
    { name: ["Popomo", "波波莫"], traitsEn: ["Naive", "Lax"], traitsKo: ["天真爛漫的", "調皮的"], Naive: [20, 0, 10, 10], Lax: [10, 10, 0, 30] },
    { name: ["Baal", "巴力"], traitsEn: ["Brave", "Quiet"], traitsKo: ["勇敢的", "冷靜的"], Brave: [0, 30, 15, 15], Quiet: [0, 5, 20, 5] },
    { name: ["Ilios", "伊利奧斯"], traitsEn: ["Brave", "Smart"], traitsKo: ["勇敢的", "聰明的"], Brave: [0, 20, 10, 10], Smart: [0, 0, 0, 30] },
    { name: ["Liberte", "利貝特"], traitsEn: ["Calm", "Hardy"], traitsKo: ["沉穩的", "努力的"], Calm: [5, 0, 20, 5], Hardy: [0, 0, 20, 0] },
    { name: ["Lalux", "拉魯茲龍"], traitsEn: ["Brave", "Smart"], traitsKo: ["勇敢的", "聰明的"], Brave: [0, 30, 10, 10], Smart: [10, 0, 0, 20] },
    { name: ["Vefal", "威臂龍"], traitsEn: ["quickWitted", "Smart"], traitsKo: ["眼尖的", "聰明的"], quickWitted: [30, 0, 5, 0], Smart: [5, 0, 0, 20] },
    { name: ["Mithra", "密特拉"], traitsEn: ["Careful", "Brave"], traitsKo: ["慎重的", "勇敢的"], Careful: [10, 10, 30, 0], Brave: [0, 25, 10, 10] },
    { name: ["Taabire", "塔比雷"], traitsEn: ["Quiet", "Brave"], traitsKo: ["冷靜的", "勇敢的"], Quiet: [0, 10, 25, 10], Brave: [0, 20, 10, 10] },
    { name: ["Rekmall", "雷克默爾龍"], traitsEn: ["Docile", "Calm"], traitsKo: ["溫和的", "沉穩的"], Docile: [0, 10, 10, 30], Calm: [10, 0, 25, 10] },
    { name: ["Nox", "諾克斯"], traitsEn: ["Brave", "Quiet"], traitsKo: ["勇敢的", "冷靜的"], Brave: [0, 20, 10, 10], Quiet: [0, 10, 20, 10] },
    { name: ["Blue Dragon", "青龍"], traitsEn: ["Docile", "Rash"], traitsKo: ["溫和的", "莽撞的"], Docile: [0, 5, 5, 20], Rash: [20, 10, 0, 10] },
    { name: ["Devared", "德瓦紅龍"], traitsEn: ["Brave", "Smart"], traitsKo: ["勇敢的", "聰明的"], Brave: [0, 20, 5, 5], Smart: [10, 0, 0, 20] },
    { name: ["Irondeva", "鋼鐵德瓦"], traitsEn: ["quickWitted", "Careful"], traitsKo: ["眼尖的", "慎重的"], quickWitted: [20, 0, 0, 10], Careful: [5, 5, 20, 0] },
    { name: ["Knight Dragon", "騎士龍"], traitsEn: ["Brave", "Smart"], traitsKo: ["勇敢的", "聰明的"], Brave: [0, 30, 10, 10], Smart: [10, 0, 0, 20] },
    { name: ["Water Dragon", "水龍"], traitsEn: ["Docile", "Naive"], traitsKo: ["溫和的", "天真爛漫的"], Docile: [0, 10, 10, 20], Naive: [20, 0, 10, 10] },
    { name: ["Hyeonmu", "玄武"], traitsEn: ["Brave", "Bold"], traitsKo: ["勇敢的", "大膽的"], Brave: [0, 20, 5, 5], Bold: [0, 30, 0, 10] },
    { name: ["Afrit", "伊弗利特"], traitsEn: ["Quiet", "quickWitted"], traitsKo: ["冷靜的", "眼尖的"], Quiet: [0, 10, 25, 10], quickWitted: [30, 10, 0, 0] },
    { name: ["Hell Dragon", "地獄龍"], traitsEn: ["Quirky", "quickWitted"], traitsKo: ["反覆無常的", "眼尖的"], Quirky: [15, 30, 0, 15], quickWitted: [20, 10, 0, 0] },
    { name: ["Redbull Dragon", "紅牛龍"], traitsEn: ["Adamant", "Quiet"], traitsKo: ["固執的", "冷靜的"], Adamant: [10, 25, 10, 0], Quiet: [0, 5, 20, 5] },
    { name: ["Gust", "格斯特"], traitsEn: ["Hasty", "Adamant"], traitsKo: ["急躁的", "固執的"], Hasty: [25, 10, 10, 0], Adamant: [5, 20, 5, 0] },
    { name: ["Marino", "馬里諾"], traitsEn: ["Brave", "Rash"], traitsKo: ["勇敢的", "莽撞的"], Brave: [0, 25, 10, 10], Rash: [25, 10, 0, 10] },
    { name: ["Egg Dragon", "蛋龍"], traitsEn: ["Adamant", "Docile"], traitsKo: ["固執的", "溫和的"], Adamant: [10, 25, 10, 0], Docile: [0, 5, 5, 20] },
    { name: ["Anemone", "葵丑龍"], traitsEn: ["Docile", "Bashful"], traitsKo: ["溫和的", "害羞的"], Docile: [0, 5, 5, 20], Bashful: [10, 0, 10, 20] },
    { name: ["Typhoon Dragon", "颱風龍"], traitsEn: ["Quirky", "quickWitted"], traitsKo: ["反覆無常的", "眼尖的"], Quirky: [10, 25, 0, 10], quickWitted: [20, 5, 0, 0] },
    { name: ["Alien Dragon", "外星龍"], traitsEn: ["Docile", "Smart"], traitsKo: ["溫和的", "聰明的"], Docile: [0, 15, 15, 30], Smart: [0, 0, 0, 25] },
    { name: ["Libera", "利維拉"], traitsEn: ["Adamant", "Careful"], traitsKo: ["固執的", "慎重的"], Adamant: [5, 20, 5, 0], Careful: [5, 5, 20, 0] },
    { name: ["Rock Dragon", "岩龍"], traitsEn: ["Adamant", "Bold"], traitsKo: ["固執的", "大膽的"], Adamant: [10, 25, 10, 0], Bold: [5, 20, 0, 0] },
    { name: ["Goldie", "金雕龍"], traitsEn: ["Bold", "Lax"], traitsKo: ["大膽的", "調皮的"], Bold: [0, 30, 10, 0], Lax: [15, 15, 0, 30] },
    { name: ["Asti", "阿斯蒂"], traitsEn: ["Docile", "Bold"], traitsKo: ["溫和的", "大膽的"], Docile: [0, 5, 5, 20], Bold: [0, 20, 10, 0] },
    { name: ["Karura", "迦樓羅"], traitsEn: ["Calm", "Quiet"], traitsKo: ["沉穩的", "冷靜的"], Calm: [5, 0, 20, 5], Quiet: [0, 15, 30, 15] },
    { name: ["Serpent Dragon", "蛇龍"], traitsEn: ["Hardy", "Lax"], traitsKo: ["努力的", "調皮的"], Hardy: [0, 0, 25, 0], Lax: [10, 10, 0, 20] },
    { name: ["Blue Lightning Dragon", "藍閃電龍"], traitsEn: ["Hasty", "Naive"], traitsKo: ["急躁的", "天真爛漫的"], Hasty: [20, 5, 5, 0], Naive: [30, 0, 10, 10] },
    { name: ["Insect Dragon", "蟲龍"], traitsEn: ["Naive", "Bashful"], traitsKo: ["天真爛漫的", "害羞的"], Naive: [20, 0, 5, 5], Bashful: [15, 0, 15, 30] },
    { name: ["Six-leg Horn", "六足角龍"], traitsEn: ["Careful", "Docile"], traitsKo: ["慎重的", "溫和的"], Careful: [10, 10, 20, 0], Docile: [0, 15, 15, 30] },
    { name: ["Khan", "可汗"], traitsEn: ["Careful", "Quiet"], traitsKo: ["慎重的", "冷靜的"], Careful: [10, 10, 25, 0], Quiet: [0, 10, 20, 10] },
    { name: ["Valla", "瓦拉"], traitsEn: ["Docile", "Brave"], traitsKo: ["溫和的", "勇敢的"], Docile: [0, 10, 10, 25], Brave: [0, 30, 15, 15] },
    { name: ["Crested Dragon", "守宮"], traitsEn: ["Lax", "quickWitted"], traitsKo: ["調皮的", "眼尖的"], Lax: [5, 5, 0, 20], quickWitted: [20, 5, 0, 0] },
    { name: ["Spicy", "辛辣龍"], traitsEn: ["Naive", "Hardy"], traitsKo: ["天真爛漫的", "努力的"], Naive: [20, 0, 5, 5], Hardy: [0, 5, 20, 0] },
    { name: ["Petra", "佩特拉龍"], traitsEn: ["Calm", "Quiet"], traitsKo: ["沉穩的", "冷靜的"], Calm: [15, 0, 30, 15], Quiet: [0, 5, 20, 5] },
    { name: ["Spike Dragon", "刺龍"], traitsEn: ["Careful", "Calm"], traitsKo: ["慎重的", "沉穩的"], Careful: [10, 10, 25, 0], Calm: [10, 0, 20, 10] },
    { name: ["Popon", "波彭"], traitsEn: ["Bashful", "Lax"], traitsKo: ["害羞的", "調皮的"], Bashful: [10, 0, 10, 20], Lax: [5, 5, 0, 20] },
    { name: ["Mustard Hammer", "芥錘龍"], traitsEn: ["Naive", "Docile"], traitsKo: ["天真爛漫的", "溫和的"], Naive: [25, 0, 10, 10], Docile: [0, 10, 10, 20] },
    { name: ["Metal Dragon", "金屬龍"], traitsEn: ["Calm", "Docile"], traitsKo: ["沉穩的", "溫和的"], Calm: [10, 0, 25, 10], Docile: [0, 5, 5, 20] },
    { name: ["Red Wyvern", "紅雙足飛龍"], traitsEn: ["Hasty", "Quirky"], traitsKo: ["急躁的", "反覆無常的"], Hasty: [20, 10, 10, 0], Quirky: [5, 20, 0, 5] },
    { name: ["Fat", "胖胖龍"], traitsEn: ["Calm", "Docile"], traitsKo: ["慎重的", "溫和的"], Calm: [10, 0, 25, 10], Docile: [0, 10, 10, 20] },
    { name: ["Taygeta", "泰吉塔"], traitsEn: ["Careful", "Quiet"], traitsKo: ["慎重的", "冷靜的"], Careful: [10, 10, 25, 0], Quiet: [0, 10, 20, 10] },
    { name: ["Siamese Dragon", "連體龍"], traitsEn: ["quickWitted", "Hasty"], traitsKo: ["眼尖的", "急躁的"], quickWitted: [25, 0, 0, 0], Hasty: [20, 5, 5, 0] },
    { name: ["Purple Lips", "紫晶龍"], traitsEn: ["Smart", "Docile"], traitsKo: ["聰明的", "溫和的"], Smart: [0, 10, 0, 30], Docile: [0, 15, 15, 30] },
    { name: ["Mushroom Dragon", "菇龍"], traitsEn: ["Calm", "Docile"], traitsKo: ["沉穩的", "溫和的"], Calm: [10, 0, 25, 10], Docile: [0, 10, 10, 20] },
    { name: ["Lava Dragon", "熔岩龍"], traitsEn: ["Quirky", "Lax"], traitsKo: ["反覆無常的", "調皮的"], Quirky: [10, 25, 0, 10], Lax: [10, 10, 0, 20] },
    { name: ["Phoenix Dragon", "鳳凰龍"], traitsEn: ["Naive", "Docile"], traitsKo: ["天真爛漫的", "溫和的"], Naive: [20, 0, 10, 10], Docile: [0, 15, 15, 30] },
    { name: ["Wings Dragon", "翼龍"], traitsEn: ["Rash", "Bashful"], traitsKo: ["莽撞的", "수줍어하는"], Rash: [25, 10, 0, 10], Bashful: [5, 0, 5, 20] },
    { name: ["Blue Thunder", "藍雷龍"], traitsEn: ["Careful", "Docile"], traitsKo: ["慎重的", "溫和的"], Careful: [5, 5, 20, 0], Docile: [0, 10, 10, 20] },
    { name: ["Volcano Dragon", "火山龍"], traitsEn: ["Docile", "Hasty"], traitsKo: ["溫和的", "急躁的"], Docile: [0, 10, 10, 20], Hasty: [20, 10, 10, 0] },
    { name: ["Fire Dragon", "火龍"], traitsEn: ["Hasty", "Adamant"], traitsKo: ["急躁的", "固執的"], Hasty: [20, 10, 10, 0], Adamant: [5, 20, 5, 0] },
    { name: ["Nessie", "尼斯湖水怪"], traitsEn: ["Smart", "Hardy"], traitsKo: ["聰明的", "努力的"], Smart: [0, 0, 10, 30], Hardy: [5, 0, 20, 0] },
    { name: ["Ignis", "伊格尼斯"], traitsEn: ["Calm", "Docile"], traitsKo: ["沉穩的", "溫和的"], Calm: [10, 0, 20, 10], Docile: [0, 10, 10, 25] },
    { name: ["Sand Dragon", "沙龍"], traitsEn: ["Naive", "Calm"], traitsKo: ["天真爛漫的", "沉穩的"], Naive: [25, 0, 10, 10], Calm: [10, 0, 25, 10] },
    { name: ["Swamp Dragon", "沼澤龍"], traitsEn: ["Calm", "Docile"], traitsKo: ["沉穩的", "溫和的"], Calm: [5, 0, 20, 5], Docile: [0, 5, 5, 20] },
    { name: ["Wind Dragon", "風龍"], traitsEn: ["quickWitted", "Hasty"], traitsKo: ["眼尖的", "急躁的"], quickWitted: [25, 0, 0, 0], Hasty: [20, 10, 10, 0] },
    { name: ["Nello", "涅洛"], traitsEn: ["Quiet", "Brave"], traitsKo: ["冷靜的", "勇敢的"], Quiet: [0, 10, 20, 10], Brave: [0, 25, 10, 10] },
    { name: ["Frog Dragon", "蛙龍"], traitsEn: ["Quirky", "Calm"], traitsKo: ["反覆無常的", "沉穩的"], Quirky: [10, 25, 0, 10], Calm: [10, 0, 20, 10] },
    { name: ["Cloud Dragon", "雲龍"], traitsEn: ["Hasty", "Quirky"], traitsKo: ["急躁的", "反覆無常的"], Hasty: [20, 5, 5, 0], Quirky: [10, 25, 0, 10] },

    { name: ["divider", "⚡ 西尤塔勘 ❄️"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Marbas", "瑪巴斯"], traitsEn: ["Careful", "Bold"], traitsKo: ["慎重的", "大膽的"], Careful: [10, 10, 20, 0], Bold: [5, 30, 0, 0] },
    { name: ["Animala", "靈魂"], traitsEn: ["Quiet", "Adamant"], traitsKo: ["冷靜的", "固執的"], Quiet: [0, 10, 25, 10], Adamant: [10, 30, 10, 0] },
    { name: ["Berris", "貝里斯"], traitsEn: ["Docile", "Smart"], traitsKo: ["溫和的", "聰明的"], Docile: [0, 10, 10, 25], Smart: [10, 0, 0, 30] },
    { name: ["Mummy Dragon", "木乃伊"], traitsEn: ["Brave", "Adamant"], traitsKo: ["勇敢的", "固執的"], Brave: [0, 25, 10, 10], Adamant: [15, 30, 15, 0] },
    { name: ["Crookers", "克洛可"], traitsEn: ["quickWitted", "Docile"], traitsKo: ["眼尖的", "溫和的"], quickWitted: [20, 5, 0, 0], Docile: [0, 10, 10, 20] },
    { name: ["Poison River", "毒流"], traitsEn: ["Hasty", "quickWitted"], traitsKo: ["急躁的", "眼尖的"], Hasty: [25, 10, 10, 0], quickWitted: [30, 5, 0, 0] },
    { name: ["Aegis", "埃癸斯"], traitsEn: ["Bold", "Calm"], traitsKo: ["大膽的", "沉穩的"], Bold: [0, 25, 0, 5], Calm: [10, 0, 30, 10] },
    { name: ["Snow Flower Popomo", "雪花波波莫"], traitsEn: ["Docile", "Naive"], traitsKo: ["溫和的", "天真爛漫的"], Docile: [0, 10, 10, 20], Naive: [25, 0, 10, 10] },
    { name: ["Rugar", "盧迦勒"], traitsEn: ["Quiet", "Adamant"], traitsKo: ["冷靜的", "固執的"], Quiet: [0, 10, 20, 10], Adamant: [10, 30, 10, 0] },
    { name: ["Jima", "鰭摩"], traitsEn: ["Smart", "Calm"], traitsKo: ["聰明的", "沉穩的"], Smart: [0, 0, 5, 25], Calm: [10, 0, 30, 10] },
    { name: ["Fire Ghost Dragon", "火鬼"], traitsEn: ["Quirky", "Adamant"], traitsKo: ["反覆無常的", "固執的"], Quirky: [10, 30, 0, 10], Adamant: [15, 30, 15, 0] },
    { name: ["Hercules Dragon", "大力士龍"], traitsEn: ["Adamant", "Bold"], traitsKo: ["固執的", "大膽的"], Adamant: [10, 20, 10, 0], Bold: [0, 30, 0, 5] },
    { name: ["Baekho", "白虎"], traitsEn: ["Brave", "Docile"], traitsKo: ["勇敢的", "溫和的"], Brave: [0, 20, 5, 5], Docile: [0, 15, 15, 30] },
    { name: ["Sharp Tail", "尖尾龍"], traitsEn: ["Naive", "Quirky"], traitsKo: ["天真爛漫的", "反覆無常的"], Naive: [20, 0, 5, 5], Quirky: [10, 30, 0, 10] },
    { name: ["Lichmond", "里奇蒙特"], traitsEn: ["Hardy", "Quirky"], traitsKo: ["努力的", "反覆無常的"], Hardy: [0, 0, 20, 10], Quirky: [10, 20, 0, 10] },
    { name: ["Demong & Gargoyle", "鬼怪和石像鬼"], traitsEn: ["quickWitted", "Adamant"], traitsKo: ["眼尖的", "固執的"], quickWitted: [30, 0, 5, 0], Adamant: [10, 30, 10, 0] },
    { name: ["Eelos", "伊洛斯"], traitsEn: ["Lax", "Naive"], traitsKo: ["調皮的", "天真爛漫的"], Lax: [10, 10, 0, 30], Naive: [30, 0, 10, 10] },
    { name: ["Blue Firetail", "青火尾"], traitsEn: ["quickWitted", "Quirky"], traitsKo: ["眼尖的", "反覆無常的"], quickWitted: [20, 0, 0, 5], Quirky: [10, 25, 0, 10] },
    { name: ["Minas", "美那斯"], traitsEn: ["Quiet", "Calm"], traitsKo: ["冷靜的", "沉穩的"], Quiet: [0, 10, 20, 10], Calm: [10, 0, 25, 10] },
    { name: ["Dupen", "德潘"], traitsEn: ["Bold", "Quiet"], traitsKo: ["大膽的", "冷靜的"], Bold: [0, 30, 5, 0], Quiet: [0, 10, 30, 10] },
    { name: ["Ereboss", "厄瑞玻斯"], traitsEn: ["Adamant", "Quiet"], traitsKo: ["固執的", "冷靜的"], Adamant: [5, 20, 5, 0], Quiet: [0, 10, 25, 10] },
    { name: ["Jarukah", "伽盧卡"], traitsEn: ["Naive", "quickWitted"], traitsKo: ["天真爛漫的", "眼尖的"], Naive: [20, 0, 10, 10], quickWitted: [25, 0, 5, 0] },
    { name: ["Pink Bell", "粉鈴"], traitsEn: ["Quirky", "Naive"], traitsKo: ["反覆無常的", "天真爛漫的"], Quirky: [10, 25, 0, 10], Naive: [30, 0, 10, 10] },
    { name: ["Taros", "塔洛斯"], traitsEn: ["quickWitted", "Quiet"], traitsKo: ["眼尖的", "冷靜的"], quickWitted: [20, 0, 10, 0], Quiet: [0, 10, 30, 10] },
    { name: ["Mist Dragon", "霧龍"], traitsEn: ["Quirky", "Rash"], traitsKo: ["反覆無常的", "莽撞的"], Quirky: [5, 20, 0, 5], Rash: [30, 15, 0, 15] },
    { name: ["Witch Dragon", "女巫龍"], traitsEn: ["Quirky", "Bold"], traitsKo: ["反覆無常的", "大膽的"], Quirky: [10, 20, 0, 10], Bold: [0, 30, 0, 10] },
    { name: ["Skelegon", "化石龍"], traitsEn: ["quickWitted", "Rash"], traitsKo: ["眼尖的", "莽撞的"], quickWitted: [20, 10, 0, 0], Rash: [25, 10, 0, 10] },
    { name: ["Dragonoid", "安卓龍"], traitsEn: ["quickWitted", "Smart"], traitsKo: ["眼尖的", "聰明的"], quickWitted: [20, 10, 0, 0], Smart: [10, 0, 0, 30] },
    { name: ["Lambgon", "羊龍"], traitsEn: ["Calm", "Docile"], traitsKo: ["沉穩的", "溫和的"], Calm: [5, 0, 20, 5], Docile: [0, 10, 10, 20] },
    { name: ["Ninmunia", "忍莫尼亞"], traitsEn: ["Hardy", "quickWitted"], traitsKo: ["努力的", "眼尖的"], Hardy: [5, 0, 20, 0], quickWitted: [20, 10, 0, 0] },
    { name: ["Hedgebat", "刺蝟龍"], traitsEn: ["Quiet", "Careful"], traitsKo: ["冷靜的", "慎重的"], Quiet: [0, 5, 20, 5], Careful: [15, 15, 30, 0] },
    { name: ["Clockwork Dragon", "發條龍"], traitsEn: ["Docile", "Smart"], traitsKo: ["溫和的", "聰明的"], Docile: [0, 5, 5, 20], Smart: [0, 5, 0, 25] },
    { name: ["Blade Dragon", "刀鋒龍"], traitsEn: ["Brave", "Quiet"], traitsKo: ["勇敢的", "冷靜的"], Brave: [0, 20, 10, 10], Quiet: [0, 10, 20, 10] },
    { name: ["Scarlet", "史嘉雷"], traitsEn: ["Bashful", "Careful"], traitsKo: ["害羞的", "慎重的"], Bashful: [10, 0, 10, 20], Careful: [10, 10, 20, 0] },
    { name: ["Python", "巨蟒"], traitsEn: ["Quiet", "Careful"], traitsKo: ["冷靜的", "慎重的"], Quiet: [0, 5, 20, 5], Careful: [10, 10, 25, 0] },
    { name: ["Beleth", "貝雷特"], traitsEn: ["Hasty", "Adamant"], traitsKo: ["急躁的", "固執的"], Hasty: [25, 10, 10, 0], Adamant: [10, 25, 10, 0] },
    { name: ["Tattoo Dragon", "刺青龍"], traitsEn: ["Brave", "Docile"], traitsKo: ["勇敢的", "溫和的"], Brave: [0, 20, 5, 5], Docile: [0, 15, 15, 30] },
    { name: ["Titan", "泰坦"], traitsEn: ["Careful", "Docile"], traitsKo: ["慎重的", "溫和的"], Careful: [5, 5, 20, 0], Docile: [0, 5, 5, 20] },
    { name: ["Spine Dragon", "脊刺龍"], traitsEn: ["Naive", "Lax"], traitsKo: ["天真爛漫的", "調皮的"], Naive: [20, 0, 5, 5], Lax: [10, 10, 0, 20] },
    { name: ["Vera", "維拉"], traitsEn: ["Quiet", "Adamant"], traitsKo: ["冷靜的", "固執的"], Quiet: [0, 5, 20, 5], Adamant: [10, 20, 10, 0] },
    { name: ["Splender", "璀璨龍"], traitsEn: ["quickWitted", "Careful"], traitsKo: ["眼尖的", "慎重的"], quickWitted: [20, 5, 0, 0], Careful: [10, 10, 20, 0] },
    { name: ["Neon Dragon", "霓虹龍"], traitsEn: ["Calm", "Docile"], traitsKo: ["沉穩的", "溫和的"], Calm: [5, 0, 20, 5], Docile: [0, 10, 10, 25] },
    { name: ["Scorpion Dragon", "蠍龍"], traitsEn: ["Bold", "Brave"], traitsKo: ["大膽的", "勇敢的"], Bold: [5, 20, 0, 0], Brave: [0, 25, 10, 10] },
    { name: ["Hallow", "聖徒"], traitsEn: ["Quiet", "Calm"], traitsKo: ["冷靜的", "沉穩的"], Quiet: [0, 10, 20, 10], Calm: [10, 0, 25, 10] },
    { name: ["Haetae", "獬豸"], traitsEn: ["Brave", "Bold"], traitsKo: ["勇敢的", "大膽的"], Brave: [0, 20, 5, 5], Bold: [0, 20, 10, 0] },
    { name: ["Devilgon", "魔鬼龍"], traitsEn: ["Quiet", "Adamant"], traitsKo: ["冷靜的", "固執的"], Quiet: [0, 10, 20, 10], Adamant: [10, 25, 10, 0] },

    { name: ["divider", "🕔 05月限定 🕔"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Smart Dragon", "智龍"], traitsEn: ["Smart", "Docile"], traitsKo: ["聰明的", "溫和的"], Smart: [0, 10, 0, 20], Docile: [0, 5, 5, 20] },
    { name: ["Vegabond", "浪人龍"], traitsEn: ["Bold", "Quiet"], traitsKo: ["大膽的", "冷靜的"], Bold: [10, 30, 0, 0], Quiet: [0, 5, 20, 5] },
    { name: ["Caracen", "彩紋龍"], traitsEn: ["Lax", "Naive"], traitsKo: ["調皮的", "天真爛漫的"], Lax: [15, 15, 0, 30], Naive: [25, 0, 10, 10] },
    { name: ["divider", "🕕 06月限定 🕕"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Goblin Dragon", "鬼怪"], traitsEn: ["Naive", "Brave"], traitsKo: ["天真爛漫的", "勇敢的"], Naive: [25, 0, 10, 10], Brave: [0, 25, 10, 10] },
    { name: ["Rupo", "陸波"], traitsEn: ["Bold", "Quiet"], traitsKo: ["大膽的", "冷靜的"], Bold: [0, 30, 10, 0], Quiet: [0, 10, 20, 10] },
    { name: ["Ninja Dragon", "忍者龍"], traitsEn: ["Careful", "quickWitted"], traitsKo: ["慎重的", "眼尖的"], Careful: [5, 5, 20, 0], quickWitted: [20, 0, 5, 0] },
    { name: ["divider", "🕖 07月限定 🕖"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Skoorum", "斯庫魯	"], traitsEn: ["Hasty", "Adamant"], traitsKo: ["急躁的", "固執的"], Hasty: [30, 10, 10, 0], Adamant: [10, 30, 10, 0] },
    { name: ["Gracia", "格拉齊亞"], traitsEn: ["Brave", "quickWitted"], traitsKo: ["勇敢的", "眼尖的"], Brave: [0, 20, 10, 10], quickWitted: [20, 10, 0, 0] },
    { name: ["Maga", "馬珈"], traitsEn: ["Bold", "Naive"], traitsKo: ["大膽的", "天真爛漫的"], Bold: [0, 30, 10, 0], Naive: [20, 0, 10, 10] },
    { name: ["divider", "🕗 08月限定 🕗"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Oculus", "歐庫洛斯"], traitsEn: ["Smart", "quickWitted"], traitsKo: ["聰明的", "眼尖的"], Smart: [10, 0, 0, 30], quickWitted: [30, 10, 0, 0] },
    { name: ["Mellow", "梅洛"], traitsEn: ["Smart", "Rash"], traitsKo: ["聰明的", "莽撞的"], Smart: [5, 0, 0, 30], Rash: [20, 10, 0, 10] },
    { name: ["Gaian", "蓋安"], traitsEn: ["Bold", "Calm"], traitsKo: ["大膽的", "沉穩的"], Bold: [0, 30, 10, 0], Calm: [5, 0, 20, 5] },
    { name: ["divider", "🕘 09月限定 🕘"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Stra", "絲特拉龍"], traitsEn: ["Docile", "Naive"], traitsKo: ["溫和的", "天真爛漫的"], Docile: [0, 5, 5, 20], Naive: [20, 0, 5, 5] },
    { name: ["Maldek", "馬爾戴克龍"], traitsEn: ["Rash", "Lax"], traitsKo: ["莽撞的", "調皮的"], Rash: [20, 10, 0, 10], Lax: [15, 15, 0, 30] },
    { name: ["Slosi", "鎖洛斯龍"], traitsEn: ["Adamant", "Careful"], traitsKo: ["固執的", "慎重的"], Adamant: [20, 10, 0, 10], Careful: [15, 15, 0, 30] },
    { name: ["divider", "🕙 10月限定 🕙"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Agnad", "亞格納德"], traitsEn: ["Smart", "Calm"], traitsKo: ["聰明的", "沉穩的"], Smart: [0, 5, 0, 20], Calm: [10, 0, 30, 10] },
    { name: ["Leo Vector", "獅貝特"], traitsEn: ["Smart", "Adamant"], traitsKo: ["聰明的", "固執的"], Smart: [0, 10, 0, 20], Adamant: [10, 25, 10, 0] },
    { name: ["Gautling-Gon", "格林"], traitsEn: ["Quiet", "Bold"], traitsKo: ["冷靜的", "大膽的"], Quiet: [0, 5, 20, 5], Bold: [0, 20, 0, 10] },
    { name: ["divider", "🕚 11月限定 🕚"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Demonio", "戴莫尼奧"], traitsEn: ["Quiet", "Docile"], traitsKo: ["冷靜的", "溫和的"], Quiet: [0, 10, 20, 10], Docile: [0, 0, 0, 30] },
    { name: ["Ges", "晶翅"], traitsEn: ["Brave", "Smart"], traitsKo: ["勇敢的", "聰明的"], Brave: [0, 20, 5, 5], Smart: [10, 0, 0, 20] },
    { name: ["Gigantis", "巨龍靈"], traitsEn: ["Quiet", "Adamant"], traitsKo: ["冷靜的", "固執的"], Quiet: [0, 15, 30, 15], Adamant: [15, 30, 15, 0] },

    { name: ["divider", "💕 配種龍 💕"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Girdletail Dragon", "鎧蜥龍"], traitsEn: ["Bold", "Rash"], traitsKo: ["大膽的", "莽撞的"], Bold: [10, 30, 0, 0], Rash: [25, 10, 0, 10] },
    { name: ["Angel Jr", "天使龍二世"], traitsEn: ["Calm", "Smart"], traitsKo: ["沉穩的", "聰明的"], Calm: [10, 0, 30, 10], Smart: [0, 5, 0, 30] },
    { name: ["God Jr", "古代神龍二世"], traitsEn: ["Brave", "Hasty"], traitsKo: ["勇敢的", "急躁的"], Brave: [0, 30, 15, 15], Hasty: [30, 10, 10, 0] },
    { name: ["Frost Blue Dragon", "冰河青龍"], traitsEn: ["Quiet", "Bashful"], traitsKo: ["冷靜的", "害羞的"], Quiet: [0, 10, 25, 10], Bashful: [10, 0, 10, 30] },
    { name: ["Hydragon", "多頭龍"], traitsEn: ["Adamant", "Hasty"], traitsKo: ["固執的", "急躁的"], Adamant: [10, 20, 10, 0], Hasty: [20, 5, 5, 0] },
    { name: ["Jimon", "吉蒙"], traitsEn: ["quickWitted", "Smart"], traitsKo: ["眼尖的", "聰明的"], quickWitted: [25, 0, 0, 0], Smart: [10, 0, 0, 20] },
    { name: ["Labasalt", "火山鹽龍"], traitsEn: ["Adamant", "Calm"], traitsKo: ["固執的", "沉穩的"], Adamant: [15, 30, 15, 0], Calm: [10, 0, 20, 10] },
    { name: ["Magnello", "火涅羅龍"], traitsEn: ["Rash", "Hasty"], traitsKo: ["莽撞的", "急躁的"], Rash: [20, 10, 0, 10], Hasty: [30, 10, 10, 0] },
    { name: ["Khan Marino", "可汗馬里諾"], traitsEn: ["Adamant", "Hasty"], traitsKo: ["固執的", "急躁的"], Adamant: [10, 25, 10, 0], Hasty: [20, 10, 10, 0] },
    { name: ["White Gold", "白金龍"], traitsEn: ["Bold", "Calm"], traitsKo: ["大膽的", "沉穩的"], Bold: [10, 20, 0, 0], Calm: [15, 0, 30, 15] },
    { name: ["Rose Gold", "玫瑰金龍"], traitsEn: ["Bashful", "Calm"], traitsKo: ["害羞的", "沉穩的"], Bashful: [10, 0, 10, 25], Calm: [5, 0, 20, 5] },
    { name: ["Dragonoid Soul", "安卓靈魂龍"], traitsEn: ["Quiet", "Smart"], traitsKo: ["冷靜的", "聰明的"], Quiet: [0, 10, 20, 10], Smart: [0, 0, 5, 30] },
    { name: ["Hourglass Dragon", "沙漏龍"], traitsEn: ["Smart", "Calm"], traitsKo: ["聰明的", "沉穩的"], Smart: [0, 5, 0, 20], Calm: [10, 0, 25, 10] },
    { name: ["Leglien", "足化外星龍"], traitsEn: ["Hardy", "Careful"], traitsKo: ["努力的", "慎重的"], Hardy: [10, 0, 30, 0], Careful: [10, 10, 25, 0] },
    { name: ["Chungmu Haetae", "忠武獬豸"], traitsEn: ["Brave", "Bold"], traitsKo: ["勇敢的", "大膽的"], Brave: [0, 20, 5, 5], Bold: [10, 30, 0, 0] },
    { name: ["Mud Dragon", "泥龍"], traitsEn: ["Quiet", "Adamant"], traitsKo: ["冷靜的", "固執的"], Quiet: [0, 5, 20, 5], Adamant: [10, 20, 10, 0] },
    { name: ["Gold Pike", "金刺龍"], traitsEn: ["Hasty", "Lax"], traitsKo: ["急躁的", "調皮的"], Hasty: [25, 10, 10, 0], Lax: [10, 10, 0, 20] },
    { name: ["Red Taabire", "紅塔比雷"], traitsEn: ["Hasty", "Quirky"], traitsKo: ["急躁的", "反覆無常的"], Hasty: [30, 15, 15, 0], Quirky: [10, 25, 0, 10] },
    { name: ["Vonsharkgon", "風鯊"], traitsEn: ["Rash", "Bashful"], traitsKo: ["莽撞的", "害羞的"], Rash: [30, 15, 0, 15], Bashful: [10, 0, 10, 30] },
    { name: ["Tycane", "泰伊肯"], traitsEn: ["Quirky", "Hasty"], traitsKo: ["反覆無常的", "急躁的"], Quirky: [10, 20, 0, 10], Hasty: [20, 10, 10, 0] },
    { name: ["Tediblo", "泰迪布羅"], traitsEn: ["Hasty", "Quiet"], traitsKo: ["急躁的", "冷靜的"], Hasty: [30, 10, 10, 0], Quiet: [0, 10, 30, 10] },
    { name: ["Dark Cloud Dragon", "烏雲龍"], traitsEn: ["Naive", "Quirky"], traitsKo: ["天真爛漫的", "反覆無常的"], Naive: [30, 0, 10, 10], Quirky: [10, 20, 0, 10] },
    { name: ["Cobra Dragon", "眼鏡蛇龍"], traitsEn: ["Quirky", "Adamant"], traitsKo: ["反覆無常的", "固執的"], Quirky: [10, 30, 0, 10], Adamant: [10, 25, 10, 0] },
    { name: ["Serpent Flower", "蛇花龍"], traitsEn: ["quickWitted", "Quirky"], traitsKo: ["眼尖的", "反覆無常的"], quickWitted: [30, 10, 0, 0], Quirky: [10, 20, 0, 10] },
    { name: ["Mushroom Knight", "菇騎士龍"], traitsEn: ["Calm", "Brave"], traitsKo: ["沉穩的", "勇敢的"], Calm: [5, 0, 20, 5], Brave: [0, 20, 10, 10] },
    { name: ["Gold Metal", "黃金金屬龍"], traitsEn: ["Hasty", "Bold"], traitsKo: ["急躁的", "大膽的"], Hasty: [20, 10, 10, 0], Bold: [10, 25, 0, 0] },
    { name: ["Black Armor Sword", "黑甲劍龍"], traitsEn: ["Brave", "Hardy"], traitsKo: ["勇敢的", "努力的"], Brave: [0, 30, 15, 15], Hardy: [5, 0, 30, 0] },
    { name: ["Black Armor Spear", "黑甲長矛龍"], traitsEn: ["quickWitted", "Careful"], traitsKo: ["眼尖的", "慎重的"], quickWitted: [20, 5, 0, 0], Careful: [10, 10, 30, 0] },
    { name: ["Blue Characen", "藍彩紋龍"], traitsEn: ["Bashful", "Adamant"], traitsKo: ["害羞的", "固執的"], Bashful: [15, 0, 15, 30], Adamant: [15, 30, 15, 0] },
    { name: ["Light Spicy", "微辣龍"], traitsEn: ["Calm", "Docile"], traitsKo: ["沉穩的", "溫和的"], Calm: [5, 0, 20, 5], Docile: [0, 10, 10, 30] },
    { name: ["mongsuryong", "夢水龍"], traitsEn: ["Calm", "Smart"], traitsKo: ["沉穩的", "聰明的"], Calm: [10, 0, 20, 10], Smart: [10, 0, 0, 20] },

    { name: ["divider", "💡 任務龍 💡"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Banshee", "女妖"], traitsEn: ["Quiet", "Quirky"], traitsKo: ["冷靜的", "反覆無常的"], Quiet: [0, 10, 20, 10], Quirky: [10, 25, 0, 10] },
    { name: ["Solar Dragon", "太陽龍"], traitsEn: ["Lax", "Naive"], traitsKo: ["調皮的", "天真爛漫的"], Lax: [15, 15, 0, 30], Naive: [30, 0, 15, 15] },
    { name: ["Timber Dragon", "木龍"], traitsEn: ["Docile", "Adamant"], traitsKo: ["溫和的", "固執的"], Docile: [0, 10, 10, 25], Adamant: [10, 30, 10, 0] },
    { name: ["Firetail", "火尾龍"], traitsEn: ["quickWitted", "Quirky"], traitsKo: ["眼尖的", "反覆無常的"], quickWitted: [25, 0, 0, 0], Quirky: [10, 25, 0, 10] },
    { name: ["Elderly Dragon", "古龍"], traitsEn: ["Adamant", "Calm"], traitsKo: ["固執的", "沉穩的"], Adamant: [5, 20, 5, 0], Calm: [10, 0, 20, 10] },
    { name: ["Nessiebig", "尼斯湖大水怪"], traitsEn: ["Quiet", "Hasty"], traitsKo: ["冷靜的", "急躁的"], Quiet: [0, 15, 30, 15], Hasty: [20, 10, 10, 0] },
    { name: ["Citael", "西塔爾"], traitsEn: ["Calm", "Docile"], traitsKo: ["沉穩的", "溫和的"], Calm: [15, 0, 30, 15], Docile: [0, 10, 10, 20] },
    { name: ["Flame Dragon", "炎龍"], traitsEn: ["Careful", "Calm"], traitsKo: ["慎重的", "沉穩的"], Careful: [5, 5, 20, 0], Calm: [10, 0, 20, 10] },
    { name: ["Flower Dragon", "花龍"], traitsEn: ["Bashful", "Rash"], traitsKo: ["害羞的", "莽撞的"], Bashful: [10, 0, 10, 30], Rash: [20, 10, 0, 10] },
    { name: ["Enoki Mushroom Dragon", "金針菇龍"], traitsEn: ["Adamant", "Rash"], traitsKo: ["固執的", "莽撞的"], Adamant: [10, 30, 10, 0], Rash: [25, 10, 0, 10] },
    { name: ["Artemis", "阿提米絲"], traitsEn: ["Docile", "Calm"], traitsKo: ["溫和的", "沉穩的"], Docile: [0, 10, 10, 20], Calm: [10, 0, 30, 10] },
    { name: ["Azak", "阿薩克"], traitsEn: ["Careful", "Smart"], traitsKo: ["慎重的", "聰明的"], Careful: [5, 5, 20, 0], Smart: [0, 0, 10, 30] },
    { name: ["Star Ace", "星艾思"], traitsEn: ["Calm", "Adamant"], traitsKo: ["沉穩的", "固執的"], Calm: [15, 0, 30, 15], Adamant: [15, 30, 15, 0] },
    { name: ["Patroa", "派特羅亞"], traitsEn: ["Naive", "Hardy"], traitsKo: ["天真爛漫的", "努力的"], Naive: [20, 0, 5, 5], Hardy: [0, 0, 25, 0] },
    { name: ["Sura Dragon", "修羅龍"], traitsEn: ["Adamant", "Bold"], traitsKo: ["固執的", "大膽的"], Adamant: [5, 20, 5, 0], Bold: [0, 20, 10, 0] },
    { name: ["Vargr", "座狼"], traitsEn: ["Quiet", "Adamant"], traitsKo: ["冷靜的", "固執的"], Quiet: [0, 5, 20, 5], Adamant: [10, 25, 10, 0] },
    { name: ["Kuzmara", "庫茲馬拉"], traitsEn: ["Brave", "Careful"], traitsKo: ["勇敢的", "慎重的"], Brave: [0, 25, 10, 10], Careful: [10, 10, 25, 0] },
    { name: ["Teddy Dragon", "泰迪龍"], traitsEn: ["Naive", "Docile"], traitsKo: ["天真爛漫的", "溫和的"], Naive: [25, 0, 10, 10], Docile: [0, 15, 15, 30] },
    { name: ["Maloden", "馬洛登"], traitsEn: ["Quiet", "Bold"], traitsKo: ["冷靜的", "大膽的"], Quiet: [0, 5, 20, 5], Bold: [0, 20, 0, 5] },
    { name: ["Abyssedge", "深淵利刃龍"], traitsEn: ["Quiet", "Adamant"], traitsKo: ["冷靜的", "固執的"], Quiet: [0, 15, 30, 15], Adamant: [5, 20, 5, 0] },
    { name: ["Lololli", "棒棒糖"], traitsEn: ["quickWitted", "Smart"], traitsKo: ["眼尖的", "聰明的"], quickWitted: [30, 0, 0, 10], Smart: [0, 0, 0, 25] },
    { name: ["Centura", "聖圖拉"], traitsEn: ["Careful", "Adamant"], traitsKo: ["慎重的", "固執的"], Careful: [10, 10, 25, 0], Adamant: [10, 25, 10, 0] },
    { name: ["Leaf Dragon", "葉龍"], traitsEn: ["Naive", "Rash"], traitsKo: ["天真爛漫的", "莽撞的"], Naive: [25, 0, 10, 10], Rash: [20, 10, 0, 10] },
    { name: ["Totem Dragon", "圖騰龍"], traitsEn: ["Careful", "Calm"], traitsKo: ["慎重的", "沉穩的"], Careful: [10, 10, 25, 0], Calm: [5, 0, 20, 5] },
    { name: ["Deva", "德瓦"], traitsEn: ["Adamant", "Quiet"], traitsKo: ["固執的", "冷靜的"], Adamant: [5, 20, 5, 0], Quiet: [0, 5, 20, 5] },
    { name: ["T-Rex Dragon", "暴龍"], traitsEn: ["Hasty", "Quirky"], traitsKo: ["急躁的", "反覆無常的"], Hasty: [30, 15, 15, 0], Quirky: [15, 30, 0, 15] },
    { name: ["Bonehead", "骷髏龍"], traitsEn: ["Quirky", "Bashful"], traitsKo: ["反覆無常的", "害羞的"], Quirky: [5, 20, 0, 5], Bashful: [15, 0, 15, 30] },
    { name: ["Catsgon", "貓龍"], traitsEn: ["quickWitted", "Quirky"], traitsKo: ["眼尖的", "反覆無常的"], quickWitted: [30, 10, 0, 0], Quirky: [10, 20, 0, 10] },
    { name: ["Haze", "霧霾龍"], traitsEn: ["Calm", "quickWitted"], traitsKo: ["沉穩的", "眼尖的"], Calm: [10, 0, 20, 10], quickWitted: [30, 10, 0, 0] },

    { name: ["divider", "🎲 其他 🎲"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Light Darknix", "光明黑暗尼斯龍"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Abvalle", "阿拂瓦利龍"], traitsEn: ["Careful", "Adamant"], traitsKo: ["慎重的", "固執的"], Careful: [5, 5, 20, 0], Adamant: [5, 20, 5, 0] },
    { name: ["Diyona", "狄耀納"], traitsEn: ["Calm", "Docile"], traitsKo: ["沉穩的", "溫和的"], Calm: [5, 0, 20, 5], Docile: [0, 10, 10, 20] },
    { name: ["Frankenstein Dragon", "科學怪人"], traitsEn: ["Docile", "Hardy"], traitsKo: ["溫和的", "努力的"], Docile: [0, 5, 5, 20], Hardy: [5, 0, 25, 0] },
    { name: ["Mystictiny", "神秘帝尼"], traitsEn: ["Smart", "Rash"], traitsKo: ["聰明的", "莽撞的"], Smart: [0, 5, 5, 20], Rash: [5, 0, 25, 0] },
    { name: ["Adela", "雅戴拉"], traitsEn: ["Bold", "Hardy"], traitsKo: ["大膽的", "目前未知"], Bold: [0, 5, 5, 20], unknown: [5, 0, 25, 0] },
    { name: ["Light Darknix", "書記龍"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Lady Dragon", "女神"], traitsEn: ["quickWitted", "Quirky"], traitsKo: ["眼尖的", "反覆無常的"], quickWitted: [20, 0, 0, 10], Quirky: [5, 20, 0, 5] },
    { name: ["Sky Lancer", "天空槍兵"], traitsEn: ["Quiet", "Brave"], traitsKo: ["冷靜的", "勇敢的"], Quiet: [0, 10, 20, 10], Brave: [0, 30, 15, 15] },
    { name: ["Bagma", "巴葛瑪"], traitsEn: ["Docile", "Calm"], traitsKo: ["溫和的", "沉穩的"], Docile: [0, 5, 5, 20], Calm: [10, 0, 20, 10] },
    { name: ["Angra", "安格拉"], traitsEn: ["Hasty", "Adamant"], traitsKo: ["急躁的", "固執的"], Hasty: [25, 10, 10, 0], Adamant: [10, 30, 10, 0] },
    { name: ["Granos", "格拉諾思"], traitsEn: ["Smart", "Careful"], traitsKo: ["聰明的", "慎重的"], Smart: [5, 0, 0, 20], Careful: [10, 10, 30, 0] },
    { name: ["Gold Dragon", "黃金龍"], traitsEn: ["Docile", "Calm"], traitsKo: ["溫和的", "沉穩的"], Docile: [0, 5, 5, 20], Calm: [10, 0, 15, 10] },
    { name: ["Daros", "達羅斯"], traitsEn: ["Careful", "Quiet"], traitsKo: ["慎重的", "冷靜的"], Careful: [15, 15, 30, 0], Quiet: [0, 15, 30, 15] },
    { name: ["White Dragon", "白龍"], traitsEn: ["Smart", "Docile"], traitsKo: ["聰明的", "溫和的"], Smart: [0, 10, 0, 30], Docile: [0, 5, 5, 20] },
    { name: ["Black Dragon", "黑龍"], traitsEn: ["Quiet", "Careful"], traitsKo: ["冷靜的", "慎重的"], Quiet: [0, 5, 20, 5], Careful: [5, 5, 20, 0] },
    { name: ["Tutankhagon", "圖坦卡門"], traitsEn: ["traitsKo", "Careful"], traitsKo: ["沉穩的", "慎重的"], Calm: [10, 0, 30, 10], Careful: [10, 10, 30, 0] },
    { name: ["Shadow", "影龍"], traitsEn: ["quickWitted", "Calm"], traitsKo: ["眼尖的", "沉穩的"], quickWitted: [20, 0, 0, 5], Calm: [5, 0, 20, 5] },
    { name: ["Glaone", "格羅歐奈"], traitsEn: ["Smart", "Brave"], traitsKo: ["聰明的", "勇敢的"], Smart: [0, 5, 0, 20], Brave: [0, 25, 10, 10] },
    { name: ["Lakion", "洛基溫"], traitsEn: ["Quirky", "Careful"], traitsKo: ["反覆無常的", "慎重的"], Quirky: [10, 25, 0, 10], Careful: [10, 10, 20, 0] },

    { name: ["divider", "❌ 尚未開放 ❌"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["White Applecheek", "白蘋果肌龍"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] },
    { name: ["Pharaogon", "法老"], traitsEn: ["unknown", "unknown"], traitsKo: ["目前未知", "目前未知"], unknown: [1, 1, 1, 1], unknown: [1, 1, 1, 1] }




];

const specialTraits = [
    { nameEn: "Classy", nameZh: "有格調的(3代內純種4屬過20)", stats: [20, 20, 20, 20] },
    { nameEn: "Noble", nameZh: "高貴的(5代內純種4屬過20)", stats: [20, 20, 20, 20] },
    { nameEn: "Arrogant", nameZh: "傲慢的(觀看200)", stats: [25, 25, 25, 25] },
    { nameEn: "Perfectionist", nameZh: "完美主義者", stats: [20, 20, 20, 20] },
    { nameEn: "Meticulous", nameZh: "一絲不苟的", stats: [0, 0, 0, 0] },
    { nameEn: "Capable", nameZh: "有能力的", stats: [28, 28, 28, 28] },
    { nameEn: "Immersed", nameZh: "專注的", stats: [0, 0, 0, 0] },
    { nameEn: "Dull", nameZh: "平凡的", stats: [20, 20, 20, 20] },
    // { nameEn: "ElegantTraining", nameZh: "氣度不凡的", stats: [17, 17, 17, 17] },
    // { nameEn: "Clumsy", nameZh: "笨拙的", stats: [0, 0, 0, 0] },
    // { nameEn: "Distracted", nameZh: "漫不經心的", stats: [0, 0, 0, 0] }
];


const normalTraits = [
    { nameEn: "Naive", nameZh: "天真爛漫的", highestTrait: "agility", lowestTrait: "strength" },
    { nameEn: "Rash", nameZh: "莽撞的", highestTrait: "agility", lowestTrait: "focus" },
    { nameEn: "Hasty", nameZh: "急躁的", highestTrait: "agility", lowestTrait: "intellect" },
    { nameEn: "quickWitted", nameZh: "眼尖的", highestTrait: "agility", lowestTrait: "none" },
    { nameEn: "Brave", nameZh: "勇敢的", highestTrait: "strength", lowestTrait: "agility" },
    { nameEn: "Quirky", nameZh: "反覆無常的", highestTrait: "strength", lowestTrait: "focus" },
    { nameEn: "Adamant", nameZh: "固執的", highestTrait: "strength", lowestTrait: "intellect" },
    { nameEn: "Bold", nameZh: "大膽的", highestTrait: "strength", lowestTrait: "none" },
    { nameEn: "Quiet", nameZh: "冷靜的", highestTrait: "focus", lowestTrait: "agility" },
    { nameEn: "Calm", nameZh: "沉穩的", highestTrait: "focus", lowestTrait: "strength" },
    { nameEn: "Careful", nameZh: "慎重的", highestTrait: "focus", lowestTrait: "intellect" },
    { nameEn: "Hardy", nameZh: "努力的", highestTrait: "focus", lowestTrait: "none" },
    { nameEn: "Docile", nameZh: "溫和的", highestTrait: "intellect", lowestTrait: "agility" },
    { nameEn: "Bashful", nameZh: "害羞的", highestTrait: "intellect", lowestTrait: "strength" },
    { nameEn: "Lax", nameZh: "調皮的", highestTrait: "intellect", lowestTrait: "focus" },
    { nameEn: "Smart", nameZh: "聰明的", highestTrait: "intellect", lowestTrait: "none" },
    { nameEn: "unknown", nameZh: "目前未知", highestTrait: "none", lowestTrait: "none" }
];

const statList = ["agility", "strength", "focus", "intellect"];

document.addEventListener("DOMContentLoaded", function () {
    for (let i = 0; i < dragonList.length; i++) {
        let newOption = document.createElement("option");
        newOption.setAttribute("value", dragonList[i].name[0]);
        newOption.textContent = dragonList[i].name[1];
        document.querySelector("#dragon-selector").append(newOption);
    }

    for (let i = 0; i < normalTraits.length; i++) {
        let newOption = document.createElement("option");
        newOption.setAttribute("value", normalTraits[i].nameEn);
        newOption.textContent = normalTraits[i].nameZh;
        document.querySelector("#normal-trait-selector").append(newOption);
    }

    for (let i = 0; i < specialTraits.length; i++) {
        let newOption = document.createElement("option");
        newOption.setAttribute("value", specialTraits[i].nameEn);
        if (newOption.value == "Dull") newOption.setAttribute("id", specialTraits[i].nameEn);
        newOption.textContent = specialTraits[i].nameZh;
        document.querySelector("#special-trait-selector").append(newOption);
    }
});